### ISSUE TITLE
Issues upgrading to v2.6.4 or v2.6.5 with homebrew on linux

### ISSUE THREAD

**Issue by gioamato** [Shopify/homebrew-shopify#307]
**Operation Log:**

```
==> Upgrading shopify/shopify/shopify-cli
  2.6.3 -> 2.6.5

==> /home/linuxbrew/.linuxbrew/opt/ruby/bin/gem install /home/user/.cache/Homebrew/shopify-cli-2.6.5.gem --no-docume
Last 15 lines from /home/user/.cache/Homebrew/Logs/shopify-cli/01.gem:
        from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/mkmf.rb:361:in `block in postpone'
        from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/mkmf.rb:331:in `open'
        from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/mkmf.rb:357:in `postpone'
        from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/mkmf.rb:970:in `checking_for'
        from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/mkmf.rb:1082:in `have_func'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/linuxbrew/.linuxbrew/Cellar/shopify-cli/2.6.5/extensions/x86_64-linux/3.0.0/racc-1.6.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/linuxbrew/.linuxbrew/Cellar/shopify-cli/2.6.5/gems/racc-1.6.0 for inspection.
Results logged to /home/linuxbrew/.linuxbrew/Cellar/shopify-cli/2.6.5/extensions/x86_64-linux/3.0.0/racc-1.6.0/gem_make.out

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/shopify/homebrew-shopify/issues
```

**Log File:**
`cat: /home/linuxbrew/.linuxbrew/Cellar/shopify-cli/2.6.5/extensions/x86_64-linux/3.0.0/racc-1.6.0/mkmf.log: No such file or directory`

**Comment by gioamato** [comment]
Reporting that v2.6.6 is affected too.

**Comment by creative-resort** [comment]
Run brew in debug mode and look at the log file, in order to see which part fails, which library is missing, etc.
You may find only a line starting with `gcc-5`
Make sure, gcc-5 is either available on your system, or symlinked to the plain gcc.
If gcc or any other library in the log file is not installed at all, install it.

**Comment by gioamato** [comment]
@creative-resort Thank you. Using `brew install gcc@5` solved the issue. I guess this dependency should be handled automatically during `shopify-cli` installation.
