### ISSUE TITLE
Shopify CLI not installing on mac 12.4 via homebrew.

### ISSUE THREAD

**Issue by rk4bir** [Shopify/homebrew-shopify#376]
```bash
# shopify install command 
➜  ~ brew install shopify-cli

# Error output
==> Fetching shopify-cli from gem source
==> Installing shopify-cli from shopify/shopify
==> gem install /Users/kabir/Library/Caches/Homebrew/shopify-cli-2.17.0.gem --no-document --no-wrapper --no-user-install --insta
Last 15 lines from /Users/kabir/Library/Logs/Homebrew/shopify-cli/01.gem:
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/mkmf.rb:362:in `block in postpone'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/mkmf.rb:332:in `open'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/mkmf.rb:358:in `postpone'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/mkmf.rb:1006:in `checking_for'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/mkmf.rb:1118:in `have_func'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/Cellar/shopify-cli/2.17.0/extensions/x86_64-darwin-21/3.1.0/racc-1.6.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Cellar/shopify-cli/2.17.0/gems/racc-1.6.0 for inspection.
Results logged to /usr/local/Cellar/shopify-cli/2.17.0/extensions/x86_64-darwin-21/3.1.0/racc-1.6.0/gem_make.out

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/shopify/homebrew-shopify/issues
```

**Comment by tyssen** [comment]
I've got the same problem and same error output up to `last 15 lines` which then look like
    
    2022-08-10 06:41:05 +0000

    gem
    install
    /Users/johnfaulds/Library/Caches/Homebrew/shopify-cli-2.22.0.gem
    --no-document
    --no-wrapper
    --no-user-install
    --install-dir
    /opt/homebrew/Cellar/shopify-cli/2.22.0
    --bindir
    /opt/homebrew/Cellar/shopify-cli/2.22.0/bin
    --
    --skip-cli-build


    Do not report this issue to Homebrew/brew or Homebrew/core!

    These open issues may also help:
    Shopify CLI not installing on mac 12.4 via homebrew. https://github.com/Shopify/homebrew-shopify/issues/376

@rk4bir did you ever get it resolved?

**Comment by rk4bir** [comment]
@tyssen yes and no. "Yes" because I have re-installed Monterey, "No" because I couldn't solve without having to re-install.

**Comment by tyssen** [comment]
@rk4bir Don't really want to have to do that. :/

**Comment by nfauchelle** [comment]
I had this exact same issue.
I ran `xcodebuild -runFirstLaunch` on the command line. If you look at the error dump it mentions to do that.

```
... stuff
Details:  Failed to load code for plug-in com.apple.dt.IDESimulatorAvailability (/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin)
**Please ensure Xcode packages are up-to-date — try running 'xcodebuild -runFirstLaunch'.**

NSBundle error: Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  
... more stuff
```

Once that command completed I was able to install OK.

**Comment by josephnaber** [comment]
thanks @nfauchelle `xcodebuild -runFirstLaunch` worked for me!
